### PR TITLE
Completed the Third Exercise from Microverse 

### PR DESCRIPTION
**Pull request by AsimKhan2019**
Completed the following tasks for the third exercise

Created an Owners table 
Created a Species table 
Modified animals table with species_id and owners_id 
Removed species column from the animal's table
Established the foreign key relationship table between animals and Species table 
Established the foreign key relationship table between animals and Owners table 
Added the new scripts to the schema.sql file

Added new data to the Owners table 
Added new data to the Species table 
Modified animals table with the relevant species_id from the Species table 
Modified animals table with the relevant owner_id from the Owners table 
Added these modifications to the data.sql file 

Completed the queries using the JOIN statements and saved the queries in the queries.sql 

**Saved all the results in the screenshots folder, where all the screenshots are saved.** 

The new PostgreSQL has new data types that do not support the older data types such as string, etc. The list of the new data types can be found here: 

https://www.postgresql.org/docs/current/datatype.html

P.S. There was a question in the queries to retrieve the list of animals for Dean Winchester with 0 escape attempts. Dean Winchester owns 2 animals and they have made 1 and 7 escape attempts respectively, so the query answer will always be 0. All screenshots at the end are labeled with exercise3 for easy identification.

### CODE REVIEW

**Review by thecodechaser — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @AsimKhan2019👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️



## Required Changes ♻️

- [x] Please make sure to add screenshots with the results of your queries to your Pull Request description as requested in the project requirements.

image


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AsimKhan2019** [comment]
@thecodechaser The screenshots are in the screenshots folder.

**Review by Davidosky007 — APPROVED** [review]
Hi @AsimKhan2019 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* All queries run as expected 👍 
* Proper use of Gitflow 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AsimKhan2019** [comment]
@Davidosky007 Thank you for the approval

**Pull request merged**
