### PR TITLE
Completed Today's performance exercise

### PR DESCRIPTION
**Pull request by AsimKhan2019**
Complete today's exercise on performance and data tuning on the vet_clinic database. Performed the following operations on the database: 

Alter the Owners table and added a new column email to the table. 
Altered the primary keys limit to the exact requirement of data to be inserted into the table. 
Altered and adjusted the columns to handle null values. 

Followed the newly approved data types by the new PostgreSQL version 14. The string is no longer an approved data type but the text is. 

Inserted the data into the Owners table 
Inserted data into the visits table 
Re-entered data into the visits table as execution time was less than 1000 ms.

Applied Explain Analyze statement on all 3 queries to test the execution time and result. 
Took screenshots of the results. 

**All screenshots are stored in the screenshots folder.**

Applied index to visits and owners table. 
Executed the Explain Analyze queries to test the execution. 
The execution results were faster. 

**All screenshots are stored in the screenshots folder.**

Changes were made to the database and insertion statements were applied. All changes added to the following files: 

schema.sql
data.sql
queries.sql

The following screenshots are in the screenshots folder: 

exercise-query1-analyze.png
exercise-query2-analyze.png
exercise-query3-analyze.png
exercise-query1-analyze-optimized.png
exercise-query2-analyze-optimized.png
exercise-query3-analyze-optimized.png

### CODE REVIEW

**Review by ShahierNashaat — CHANGES_REQUESTED** [review]
Hi @AsimKhan2019, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 💯 

- Correct use of GitFlow ✔️
- Descriptive commit messages ✔️
- Professional looking pull request ✔️
- Your readme looks professional ✔️

## Required Changes ♻️
- [x] Kindly provide screenshots in the PR description with the results of the `EXPLAIN ANALYZE` command for each of these queries.
* `SELECT COUNT(*) FROM visits where animal_id = 4;`
* `SELECT * FROM visits where vet_id = 2;`
* `SELECT * FROM owners where email = 'owner_18327@mail.com';`

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AsimKhan2019** [comment]
@ShahierNashaat They are all in the screenshots folder. 

exercise-query1-analyze.png
exercise-query2-analyze.png
exercise-query3-analyze.png
exercise-query1-analyze-optimized.png
exercise-query2-analyze-optimized.png
exercise-query3-analyze-optimized.png

The changes can also be viewed in the Files Changed Tab

**Review by smunozmo — APPROVED** [review]
Hi @AsimKhan2019, 👋 

## Highlights 👏 

- Excellent job addressing the last review suggestions, your DB queries are optimized! 🎉 
- Great work using the right GitHub Flow.
- Your README looks professional, well done!
- Commits are descriptive, good work.
- Linters are working properly, great job!

Your project is complete!  There is nothing else to say other than... it's time to merge it! 🚀 
Very nice work, congratulations! 🎉 

# APPROVED! 💯  💯  💯 




Cheers and Happy coding! 🤓 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AsimKhan2019** [comment]
@smunozmo Thank you for the approval.

**Review by bimbolabuari — COMMENTED** [review]
Hello @AsimKhan2019  👋,

_This is an additional review as a result of the second opinion request._

- I like that you created a screenshot folder and add the screenshots 👍 , however, kindly take note that the first code reviewer was right and the project requirements ask to add the screenshots in the PR description.
    - image

- I can see that your PR has been approved. @smunozmo, let's remember to be consistent with the previous reviewer's request if it aligns with the project requirement and code review guidelines. 👍 

Keep rocking 🚀!

**Comment by smunozmo** [comment]
Thank you @bimbolabuari 🚀

**Pull request merged**
